apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: complianceremediations.complianceoperator.compliance.openshift.io
spec:
  group: complianceoperator.compliance.openshift.io
  names:
    kind: ComplianceRemediation
    listKind: ComplianceRemediationList
    plural: complianceremediations
    singular: complianceremediation
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: ComplianceRemediation is the Schema for the complianceremediations
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ComplianceRemediationSpec defines the desired state of ComplianceRemediation
          properties:
            apply:
              description: Whether the remediation should be picked up and applied
                by the operator
              type: boolean
            machineConfigContents:
              description: The actual remediation payload
              properties:
                apiVersion:
                  description: 'APIVersion defines the versioned schema of this representation
                    of an object. Servers should convert recognized schemas to the
                    latest internal value, and may reject unrecognized values. More
                    info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
                  type: string
                kind:
                  description: 'Kind is a string value representing the REST resource
                    this object represents. Servers may infer this from the endpoint
                    the client submits requests to. Cannot be updated. In CamelCase.
                    More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
                  type: string
                metadata:
                  type: object
                spec:
                  description: MachineConfigSpec defines the desired state of MachineConfig
                  properties:
                    config:
                      description: Config is a Ignition Config object.
                      properties:
                        ignition:
                          properties:
                            config:
                              properties:
                                append:
                                  items:
                                    properties:
                                      source:
                                        type: string
                                      verification:
                                        properties:
                                          hash:
                                            type: string
                                        type: object
                                    type: object
                                  type: array
                                replace:
                                  properties:
                                    source:
                                      type: string
                                    verification:
                                      properties:
                                        hash:
                                          type: string
                                      type: object
                                  type: object
                              type: object
                            security:
                              properties:
                                tls:
                                  properties:
                                    certificateAuthorities:
                                      items:
                                        properties:
                                          source:
                                            type: string
                                          verification:
                                            properties:
                                              hash:
                                                type: string
                                            type: object
                                        type: object
                                      type: array
                                  type: object
                              type: object
                            timeouts:
                              properties:
                                httpResponseHeaders:
                                  type: integer
                                httpTotal:
                                  type: integer
                              type: object
                            version:
                              type: string
                          type: object
                        networkd:
                          properties:
                            units:
                              items:
                                properties:
                                  contents:
                                    type: string
                                  dropins:
                                    items:
                                      properties:
                                        contents:
                                          type: string
                                        name:
                                          type: string
                                      type: object
                                    type: array
                                  name:
                                    type: string
                                type: object
                              type: array
                          type: object
                        passwd:
                          properties:
                            groups:
                              items:
                                properties:
                                  gid:
                                    type: integer
                                  name:
                                    type: string
                                  passwordHash:
                                    type: string
                                  system:
                                    type: boolean
                                type: object
                              type: array
                            users:
                              items:
                                properties:
                                  create:
                                    properties:
                                      gecos:
                                        type: string
                                      groups:
                                        items:
                                          type: string
                                        type: array
                                      homeDir:
                                        type: string
                                      noCreateHome:
                                        type: boolean
                                      noLogInit:
                                        type: boolean
                                      noUserGroup:
                                        type: boolean
                                      primaryGroup:
                                        type: string
                                      shell:
                                        type: string
                                      system:
                                        type: boolean
                                      uid:
                                        type: integer
                                    type: object
                                  gecos:
                                    type: string
                                  groups:
                                    items:
                                      type: string
                                    type: array
                                  homeDir:
                                    type: string
                                  name:
                                    type: string
                                  noCreateHome:
                                    type: boolean
                                  noLogInit:
                                    type: boolean
                                  noUserGroup:
                                    type: boolean
                                  passwordHash:
                                    type: string
                                  primaryGroup:
                                    type: string
                                  shell:
                                    type: string
                                  sshAuthorizedKeys:
                                    items:
                                      type: string
                                    type: array
                                  system:
                                    type: boolean
                                  uid:
                                    type: integer
                                type: object
                              type: array
                          type: object
                        storage:
                          properties:
                            directories:
                              items:
                                type: object
                              type: array
                            disks:
                              items:
                                properties:
                                  device:
                                    type: string
                                  partitions:
                                    items:
                                      properties:
                                        guid:
                                          type: string
                                        label:
                                          type: string
                                        number:
                                          type: integer
                                        size:
                                          type: integer
                                        start:
                                          type: integer
                                        typeGuid:
                                          type: string
                                      type: object
                                    type: array
                                  wipeTable:
                                    type: boolean
                                type: object
                              type: array
                            files:
                              items:
                                type: object
                              type: array
                            filesystems:
                              items:
                                properties:
                                  mount:
                                    properties:
                                      create:
                                        properties:
                                          force:
                                            type: boolean
                                          options:
                                            items:
                                              type: string
                                            type: array
                                        type: object
                                      device:
                                        type: string
                                      format:
                                        type: string
                                      label:
                                        type: string
                                      options:
                                        items:
                                          type: string
                                        type: array
                                      uuid:
                                        type: string
                                      wipeFilesystem:
                                        type: boolean
                                    type: object
                                  name:
                                    type: string
                                  path:
                                    type: string
                                type: object
                              type: array
                            links:
                              items:
                                type: object
                              type: array
                            raid:
                              items:
                                properties:
                                  devices:
                                    items:
                                      type: string
                                    type: array
                                  level:
                                    type: string
                                  name:
                                    type: string
                                  options:
                                    items:
                                      type: string
                                    type: array
                                  spares:
                                    type: integer
                                type: object
                              type: array
                          type: object
                        systemd:
                          properties:
                            units:
                              items:
                                properties:
                                  contents:
                                    type: string
                                  dropins:
                                    items:
                                      properties:
                                        contents:
                                          type: string
                                        name:
                                          type: string
                                      type: object
                                    type: array
                                  enable:
                                    type: boolean
                                  enabled:
                                    type: boolean
                                  mask:
                                    type: boolean
                                  name:
                                    type: string
                                type: object
                              type: array
                          type: object
                      required:
                      - ignition
                      type: object
                    fips:
                      type: boolean
                    kernelArguments:
                      items:
                        type: string
                      type: array
                    osImageURL:
                      description: 'INSERT ADDITIONAL SPEC FIELDS - desired state
                        of cluster Important: Run "operator-sdk generate k8s" to regenerate
                        code after modifying this file Add custom validation using
                        kubebuilder tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html
                        OSImageURL specifies the remote location that will be used
                        to fetch the OS.'
                      type: string
                  required:
                  - config
                  - fips
                  - kernelArguments
                  - osImageURL
                  type: object
              type: object
            type:
              description: Remediation type specifies the artifact the remediation
                is based on. For now, only MachineConfig is supported
              type: string
          required:
          - apply
          type: object
        status:
          description: ComplianceRemediationStatus defines the observed state of ComplianceRemediation
          properties:
            applicationState:
              description: Whether the remediation is already applied or not
              type: string
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
