# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: complianceoperator.compliance.openshift.io/v1alpha1
kind: ComplianceRemediation
metadata:
  labels:
    complianceoperator.openshift.io/scan: example-scan
    complianceoperator.openshift.io/suite: example-suite
    machineconfiguration.openshift.io/role: worker
  name: example-remediation-worker-no-direct-root-login
  namespace: openshift-compliance
spec:
  apply: false
  type: MachineConfig
  machineConfigContents:
    apiVersion: machineconfiguration.openshift.io/v1
    kind: MachineConfig
    spec:
      fips: false
      osImageURL: ""
      kernelArguments:
        - ""
      config:
        ignition:
          version: 2.2.0
        storage:
          files:
          - contents:
              source: data:,
            filesystem: root
            mode: 0600
            path: /etc/securetty
